### ISSUE TITLE
Add Coding Standards for project

### ISSUE THREAD

**Issue by dimitrystd** [sergejey/majordomo#30]
I wanted to add new method and discovered that code has different styles inside single class. Some methods use 1 space identation, other methods 2 spaces. Would be nice to have some definition of php coding standards. All contributors will be able to configure favorite IDE and provide new well-formatted code. Legacy code will be formated during various refactorings in future.
**DoD**:
- [ ] Add php coding standards on wiki or link to readme
- [ ] Prepare continuous integration server somewhere (for example travis-ci.org)
- [ ] Configure PHP_CodeSniffer according to coding standards
- [ ] Set trigger to fail build if number of violations are increased

**Comment by cyneprepou** [comment]
+1 for code standart.

**Comment by abitrolly** [comment]
Did anybody measure what is de-facto standard for majordomo sources? I like organic 3-space indentation, which is unusual for most (all?) coding standards on the internet.

**Comment by palacex** [comment]
Imho, majordomo sources does't have any standart.

Few year's ago i wrote [Style Guide](https://github.com/palacex/MajorDoMo-Coding-Standards/wiki/MajorDoMo-Style-Guide) and [CodeSniffer rules](https://github.com/palacex/MajorDoMo-Coding-Standards) for MajorDoMo project, but nobody use it.

p.s. To bring all the sources to the same style is necessary, but in this case it is practically meaningless, since it is not a fact that the changes will fall into the main branch.

**Comment by abitrolly** [comment]
We all understand the complain, but that still doesn't answer the question - can anybody measure what are the current preferences of MajorDoMo authors?

**Comment by abitrolly** [comment]
"A foolish consistency is the hobgoblin of little minds". =)
